
on: 
    pull_request:
        branches: 
            - main
        types:
            - closed
jobs:
    build:
        strategy: 
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v7
        - uses: actions/setup-python@v7
          with:
           python-version: '3.14.6' 
           cache: 'pip'
        - name: install linux dependencies
          if: runner.os == 'Linux'
          run: |
           sudo apt-get install -y patchelf
      
        - run: python -m pip install --upgrade pip
        - run: pip install -r requirements.txt
        - uses: Nuitka/Nuitka-Action@main
          with:
            nuitka-version: main
            script-name: src/Main.py
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
              name: Build-${{ runner.os }}
              path: |
                build/*.exe
                build/*.bin
                build/*.app/**/*
                build/*.dist/**/*
              include-hidden-files: true

    release:
        permissions: 
            contents: write
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create GitHub Release
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: "latest"
            title: "Release"
            draft: false
            prerelease: false  
            files: |
                path:
