
on: 
    pull_request:
        branches: 
            - main
        types:
            - closed

jobs:
    build:
        strategy: 
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v7
        - uses: actions/setup-python@v7
          with:
           python-version: '3.14.6' 
           cache: 'pip'
        - name: install linux dependencies
          if: runner.os == 'Linux'
          run: |
           sudo apt-get install -y patchelf
      
        - run: python -m pip install --upgrade pip
        - run: pip install -r requirements.txt
        - uses: Nuitka/Nuitka-Action@main
          with:
            nuitka-version: main
            script-name: src/Main.py

        - name: Rename bin
          run: |
            if [[ "$RUNNER_OS" == "Windows" ]]; then
                mv Main.dist/Main.bin Main.dist/Copypasta-Windows.bin
            elif [[ "$RUNNER_OS" == "Linux" ]]; then
                mv Main.dist/Main.bin Main.dist/Copypasta-Linux.bin
            elif [[ "$RUNNER_OS" == "macOS" ]]; then
                mv Main.dist/Main.bin Main.dist/Copypasta-MacOS.bin
            fi
          shell: bash

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
              name: Copypasta-${{ matrix.os }}
              path: Main.dist/*

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: List downloaded files (Debugging)
          run: ls -R

        - name: Make files executable Linux
          if: runner.os == 'Linux'
          run: chmod +x Copypasta-* || true
        - name: Make files exe for Mac
          if: runner.os == 'macOS'
          run: chmod +x Copypasta-* || true
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
           tag_name: ${{ github.ref_name }}
           name: Release ${{ github.ref_name }}
           draft: false
           prerelease: false
           files: |
              Copypasta-Linux.bin
              Copypasta-Windows.bin
              Copypasta-MacOS.bin
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
